# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lite_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
import sys


class Ui_MainWindow_litetest(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow_litetest):
        MainWindow_litetest.setObjectName("MainWindow_litetest")
        MainWindow_litetest.resize(731, 298)
        self.centralwidget = QtWidgets.QWidget(MainWindow_litetest)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(50, 20, 491, 81))
        self.textEdit.setObjectName("textEdit")
        self.sendout_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.sendout_BTN.setGeometry(QtCore.QRect(600, 20, 75, 24))
        self.sendout_BTN.setObjectName("sendout_BTN")
        self.update_result_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.update_result_BTN.setGeometry(QtCore.QRect(600, 70, 75, 24))
        self.update_result_BTN.setObjectName("update_result_BTN")
        self.select_A = QtWidgets.QLabel(self.centralwidget)
        self.select_A.setGeometry(QtCore.QRect(30, 160, 51, 71))
        self.select_A.setTextFormat(QtCore.Qt.MarkdownText)
        self.select_A.setAlignment(QtCore.Qt.AlignCenter)
        self.select_A.setObjectName("select_A")
        self.select_B = QtWidgets.QLabel(self.centralwidget)
        self.select_B.setGeometry(QtCore.QRect(170, 160, 53, 71))
        self.select_B.setTextFormat(QtCore.Qt.MarkdownText)
        self.select_B.setAlignment(QtCore.Qt.AlignCenter)
        self.select_B.setObjectName("select_B")
        self.select_C = QtWidgets.QLabel(self.centralwidget)
        self.select_C.setGeometry(QtCore.QRect(310, 160, 53, 71))
        self.select_C.setTextFormat(QtCore.Qt.MarkdownText)
        self.select_C.setAlignment(QtCore.Qt.AlignCenter)
        self.select_C.setObjectName("select_C")
        self.select_D = QtWidgets.QLabel(self.centralwidget)
        self.select_D.setGeometry(QtCore.QRect(450, 160, 53, 71))
        self.select_D.setTextFormat(QtCore.Qt.MarkdownText)
        self.select_D.setAlignment(QtCore.Qt.AlignCenter)
        self.select_D.setObjectName("select_D")
        self.A_amount_LCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.A_amount_LCD.setGeometry(QtCore.QRect(80, 170, 61, 51))
        self.A_amount_LCD.setObjectName("A_amount_LCD")
        self.B_amount_LCD_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.B_amount_LCD_2.setGeometry(QtCore.QRect(220, 170, 61, 51))
        self.B_amount_LCD_2.setObjectName("B_amount_LCD_2")
        self.C_amount_LCD_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.C_amount_LCD_3.setGeometry(QtCore.QRect(360, 170, 61, 51))
        self.C_amount_LCD_3.setObjectName("C_amount_LCD_3")
        self.D_amount_LCD_4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.D_amount_LCD_4.setGeometry(QtCore.QRect(500, 170, 61, 51))
        self.D_amount_LCD_4.setObjectName("D_amount_LCD_4")

        # 关闭按钮
        self.shutdown_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.shutdown_BTN.setGeometry(QtCore.QRect(600, 120, 75, 24))
        self.shutdown_BTN.setObjectName("shutdown_BTN")
        #self.shutdown_BTN.clicked.connect(lambda: self.shutdownWindow(MainWindow_litetest))
        self.shutdown_BTN.clicked.connect(MainWindow_litetest.close)

        MainWindow_litetest.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_litetest)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 731, 22))
        self.menubar.setObjectName("menubar")
        MainWindow_litetest.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_litetest)
        self.statusbar.setObjectName("statusbar")
        MainWindow_litetest.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_litetest)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_litetest)

    def retranslateUi(self, MainWindow_litetest):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_litetest.setWindowTitle(
            _translate("MainWindow_litetest", "MainWindow"))
        self.sendout_BTN.setText(_translate("MainWindow_litetest", "发布"))
        self.update_result_BTN.setText(_translate("MainWindow_litetest", "刷新"))
        self.select_A.setText(_translate("MainWindow_litetest", "## A"))
        self.select_B.setText(_translate("MainWindow_litetest", "## B"))
        self.select_C.setText(_translate("MainWindow_litetest", "## C"))
        self.select_D.setText(_translate("MainWindow_litetest", "## D"))
        self.shutdown_BTN.setText(_translate("MainWindow_litetest", "关闭"))

    # 槽函数：关闭窗口（废案）
    # def shutdownWindow(self, MainWindow):
        # MainWindow.close()
